# Generated by Django 3.1.1 on 2021-01-27 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('tailor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('paid', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('tracking_id', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Confirmes', 'Confirmed'), ('Processing', 'Processing'), ('Ready', 'Ready'), ('Delivered', 'Delivered')], max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tailor_app.costumer')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neck', models.DecimalField(blank=True, decimal_places=3, max_digits=11, null=True)),
                ('waist', models.DecimalField(blank=True, decimal_places=3, max_digits=11, null=True)),
                ('wrist', models.DecimalField(blank=True, decimal_places=3, max_digits=11, null=True)),
                ('sleeve_length', models.DecimalField(blank=True, decimal_places=3, max_digits=11, null=True)),
                ('chest', models.DecimalField(blank=True, decimal_places=3, max_digits=11, null=True)),
                ('shoulder', models.DecimalField(blank=True, decimal_places=3, max_digits=11, null=True)),
                ('thigh', models.DecimalField(blank=True, decimal_places=3, max_digits=11, null=True)),
                ('ankle', models.DecimalField(blank=True, decimal_places=3, max_digits=11, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tailor_app.costumer')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('value', models.DecimalField(decimal_places=3, max_digits=11)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tailor_app.measurement')),
            ],
        ),
    ]
