# Generated by Django 3.1.1 on 2021-02-05 11:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tailor_app', '0004_auto_20210205_0817'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Costumer',
            new_name='Customer',
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
