# Generated by Django 3.1.1 on 2021-02-17 07:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tailor_app', '0006_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
