# Generated by Django 3.1.1 on 2021-02-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailor_app', '0007_auto_20210217_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='ankle',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='chest',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='neck',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='shoulder',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='sleeve_length',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='thigh',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='waist',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='wrist',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=11),
        ),
    ]
